version: '3.1'

volumes:
  datafeeder_uploads:
  elasticsearch_data:

services:
  smtp:
    image: camptocamp/smtp-sink:latest
    ports:
      - '2025:25'
    restart: always

  database:
    image: georchestra/database:latest
    environment:
      - POSTGRES_USER=georchestra
      - POSTGRES_PASSWORD=georchestra
    ports:
      - '15432:5432'

  ldap:
    image: georchestra/ldap:latest
    environment:
      - SLAPD_ORGANISATION=georchestra
      - SLAPD_DOMAIN=georchestra.org
      - SLAPD_PASSWORD=secret
      - SLAPD_LOG_LEVEL=32768 # See https://www.openldap.org/doc/admin24/slapdconfig.html#loglevel%20%3Clevel%3E

  console:
    image: georchestra/console:latest
    depends_on:
      - ldap
      - database
    volumes:
      - ./datadir:/etc/georchestra
    environment:
      - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
      - XMS=256M
      - XMX=1G
    ports:
      - '38080:8080'

  geoserver:
    image: georchestra/geoserver:latest
    depends_on:
      - ldap
    volumes:
      - ./datadir:/etc/georchestra
    environment:
      - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
      - XMS=256M
    ports:
      - '18080:8080'

  geonetwork:
    image: georchestra/geonetwork:latest
    depends_on:
      - console
      - database
      - elasticsearch
    volumes:
      - ./datadir:/etc/georchestra
    environment:
      - DATA_DIR=/var/lib/geonetwork_data
      - ES_HOST=elasticsearch
      - ES_PROTOCOL=http
      - ES_PORT=9200
      - JAVA_OPTIONS=-Duser.home=/tmp/jetty -Dgeorchestra.datadir=/etc/georchestra -Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
      - XMS=256M
    ports:
      - '8080:8080'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: '-Xms1g -Xmx1g'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl -s -f http://localhost:9200/_cat/health >/dev/null || exit 1',
        ]
      interval: 30s
      timeout: 10s
      retries: 10
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  datafeeder:
    image: georchestra/datafeeder:latest
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./datadir:/etc/georchestra
      - datafeeder_uploads:/tmp/datafeeder
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m
      # You can set a higher loglevel this way: (ref. https://docs.spring.io/spring-boot/docs/2.1.13.RELEASE/reference/html/boot-features-logging.html#boot-features-custom-log-levels)
      - LOGGING_LEVEL_ORG_GEORCHESTRA_DATAFEEDER=INFO
    ports:
      - 8181:8080
