name: "datafeeder"
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - '1.*'
    tags:
      - '*'

jobs:
  build:
    if: "!startsWith(github.event.head_commit.message, '[skip ci] ')"
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
    - name: "Checking out"
      uses: actions/checkout@v4

    - name: "Setting up Java"
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: 'maven'
        server-id: geOrchestra-artifactory
        server-username: ARTIFACTORY_USERNAME_REF
        server-password: ARTIFACTORY_TOKEN_REF

    - name: "Package datafeeder"
      run: ./mvnw clean package

    - name: Getting image tag
      if: github.repository == 'georchestra/datafeeder-ui' && github.actor != 'dependabot[bot]'
      id: version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: "Building docker image (frontend)"
      if: github.repository == 'georchestra/datafeeder-ui' && github.actor != 'dependabot[bot]'
      run: ./mvnw clean package docker:build -Pdocker -DskipTests -DdockerImageName=georchestra/datafeeder-frontend:${{ steps.version.outputs.VERSION }}

    - name: "Logging in docker.io"
      if: github.repository == 'georchestra/datafeeder-ui' && github.actor != 'dependabot[bot]' && github.event_name != 'pull_request'
      uses: azure/docker-login@v2
      with:
        username: '${{ secrets.DOCKER_HUB_USERNAME }}'
        password: '${{ secrets.DOCKER_HUB_PASSWORD }}'

    - name: "Update Datafeeder-UI Docker Hub Description"
      if: github.ref == 'refs/heads/main' && github.repository == 'georchestra/datafeeder-ui' && github.actor != 'dependabot[bot]' && github.event_name != 'pull_request'
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        repository: georchestra/datafeeder-frontend
        readme-filepath: ./DOCKER_HUB.md
        short-description: 'Datafeeder frontend module for the geOrchestra SDI'

    - name: "Pushing latest images to docker.io"
      if: github.ref == 'refs/heads/main' && github.repository == 'georchestra/datafeeder-ui' && github.actor != 'dependabot[bot]'
      run: |
        docker tag georchestra/datafeeder-frontend:${{ steps.version.outputs.VERSION }} georchestra/datafeeder-frontend:latest
        docker push georchestra/datafeeder-frontend:latest

    - name: "Pushing release branch or tag to docker.io (.x series)"
      if: |
        (endsWith(github.ref, '.x') || contains(github.ref, 'refs/tags/'))
        && github.repository == 'georchestra/datafeeder-ui' && github.actor != 'dependabot[bot]' && github.event_name != 'pull_request'
      run: |
        docker push georchestra/datafeeder-frontend:${{ steps.version.outputs.VERSION }}


